"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  th: {
    // Layout
    'layout.loading': 'กำลังโหลดระบบงาน...',
    'layout.overview': 'ภาพรวมระบบ',
    'layout.dashboard': 'Dashboard',
    'layout.reports': 'รายงานและสถิติ',
    'layout.storeManagement': 'จัดการร้านค้า',
    'layout.orders': 'รายการคำสั่งซื้อ',
    'layout.products': 'สินค้าทั้งหมด',
    'layout.purchaseOrders': 'สั่งซื้อสินค้า (PO)',
    'layout.stock': 'คลังสินค้า (Stock)',
    'layout.ebooks': 'หนังสือ E-Book',
    'layout.categories': 'หมวดหมู่สินค้า',
    'layout.promotions': 'โปรโมชั่น',
    'layout.customerRelation': 'ลูกค้าสัมพันธ์',
    'layout.users': 'ผู้ใช้งานระบบ',
    'layout.chat': 'ข้อความสนทนา',
    'layout.tickets': 'ระบบแจ้งปัญหา',
    'layout.reviews': 'รีวิวสินค้า',
    'layout.logout': 'ออกจากระบบ',
    'layout.title': 'Admin Workspace',
    'layout.subtitle': 'จัดการร้านค้าและลูกค้าของคุณอย่างมีประสิทธิภาพ',
    'layout.storefront': 'ดูหน้าร้าน (Storefront)',

    // Dashboard
    'dash.title': 'Dashboard',
    'dash.subtitle': 'ภาพรวมและสถิติสำคัญของระบบในรอบ 30 วันที่ผ่านมา',
    'dash.30days': '30 วันที่ผ่านมา',
    'dash.7days': '7 วันที่ผ่านมา',
    'dash.thisMonth': 'เดือนนี้',
    'dash.thisYear': 'ปีนี้',
    'dash.export': 'Export PDF',
    'dash.stat1': 'ยอดขายรวม',
    'dash.stat2': 'คำสั่งซื้อใหม่',
    'dash.stat3': 'ผู้ใช้งานใหม่',
    'dash.stat4': 'การเข้าชมระบบ',
    'dash.trendTitle': 'แนวโน้มยอดขาย',
    'dash.trendSub': 'เปรียบเทียบในแต่ละช่วงเวลา',
    'dash.trendSales': 'ยอดขาย (บาท)',
    'dash.topProducts': 'สินค้าขายดี',
    'dash.viewAll': 'ดูทั้งหมด',
    'dash.sold': 'ขายแล้ว',
    'dash.noData': 'ไม่มีข้อมูลการขาย',

    // Orders
    'order.title': 'Orders',
    'order.subtitle': 'จัดการคำสั่งซื้อและสถานะการจัดส่ง',
    'order.search': 'ค้นหาคำสั่งซื้อ...',
    'order.filter': 'ตัวกรอง',
    'order.tab.all': 'ทั้งหมด',
    'order.tab.pending': 'รอชำระเงิน',
    'order.tab.verify': 'ตรวจสอบชำระเงิน',
    'order.tab.processing': 'รอแพ็ค',
    'order.tab.ready': 'รอจัดส่ง',
    'order.tab.shipped': 'จัดส่งแล้ว',
    'order.col.id': 'รหัสคำสั่งซื้อ',
    'order.col.date': 'วันที่',
    'order.col.customer': 'ลูกค้า',
    'order.col.total': 'ยอดสุทธิ',
    'order.col.status': 'สถานะ',
    'order.col.actions': 'จัดการ',
    'order.action.waitPay': 'รอลูกค้าชำระเงิน',
    'order.action.verify': 'ยืนยันการชำระเงิน',
    'order.action.packDone': 'แพ็คเสร็จสิ้น',
    'order.action.ship': 'จัดส่ง',
    'order.action.print': 'พิมพ์ใบปะหน้า',
    'order.detail.title': 'รายละเอียดคำสั่งซื้อ',
    'order.detail.customer': 'ข้อมูลลูกค้า',
    'order.detail.shipMethod': 'ช่องทางการจัดส่ง',
    'order.detail.placedOn': 'สั่งซื้อเมื่อ:',
    'order.detail.tracking': 'หมายเลขพัสดุ',
    'order.detail.assignTracking': 'ระบุเลขพัสดุ',
    'order.detail.items': 'รายการสินค้า',
    'order.detail.paymentVerified': 'ตรวจสอบการชำระเงินแล้ว',
    'order.detail.payMethod': 'วิธีชำระเงิน:',
    'order.detail.payTime': 'เวลา:',
    'order.detail.viewSlip': 'ดูสลิปโอนเงิน',
    'order.detail.cancel': 'ยกเลิก',
    'order.detail.confirmShip': 'ยืนยันจัดส่ง',
    'order.detail.done': 'เสร็จสิ้น',
    'order.empty': 'ไม่พบคำสั่งซื้อ',

    // Categories
    'cat.title': 'Categories',
    'cat.subtitle': 'จัดการหมวดหมู่สินค้าในระบบ',
    'cat.search': 'ค้นหาหมวดหมู่...',
    'cat.new': 'เพิ่มหมวดหมู่',
    'cat.items': 'รายการ',
    'cat.edit': 'แก้ไข',

    // Products
    'prod.title': 'Products',
    'prod.subtitle': 'จัดการสินค้าทั้งหมดในร้านค้าของคุณ',
    'prod.add': 'เพิ่มสินค้าใหม่',
    'prod.filter.all': 'ทั้งหมด',
    'prod.filter.active': 'แสดงผล (Active)',
    'prod.filter.draft': 'ซ่อน (Draft)',
    'prod.search': 'ค้นหาสินค้า...',
    'prod.col.book': 'หนังสือ',
    'prod.col.type': 'ประเภท',
    'prod.col.price': 'ราคา',
    'prod.col.status': 'สถานะ',
    'prod.col.actions': 'จัดการ',
    'prod.new.title': 'เพิ่มสินค้าใหม่ (Add New Book)',
    'prod.new.subtitle': 'เพิ่มข้อมูลหนังสือเล่มใหม่เพื่อแสดงบนหน้าร้าน',
    'prod.new.basicInfo': 'ข้อมูลพื้นฐาน',
    'prod.new.name': 'ชื่อหนังสือ',
    'prod.new.namePh': 'เช่น แฮร์รี่ พอตเตอร์ เล่ม 1',
    'prod.new.author': 'ผู้แต่ง/นักเขียน',
    'prod.new.authorPh': 'ชื่อผู้แต่ง',
    'prod.new.publisher': 'สำนักพิมพ์',
    'prod.new.publisherPh': 'ชื่อสำนักพิมพ์',
    'prod.new.desc': 'รายละเอียดหนังสือ',
    'prod.new.descPh': 'เรื่องย่อ หรือรายละเอียดที่น่าสนใจ...',
    'prod.new.pricing': 'ราคาและสต็อก',
    'prod.new.price': 'ราคาขาย (฿)',
    'prod.new.cost': 'ต้นทุน (฿)',
    'prod.new.sku': 'รหัสสินค้า (SKU)',
    'prod.new.barcode': 'บาร์โค้ด / ISBN',
    'prod.new.media': 'รูปภาพหน้าปก',
    'prod.new.upload': 'คลิกเพื่ออัปโหลด',
    'prod.new.uploadSub': 'หรือลากไฟล์วางที่นี่ (PNG, JPG ขนาดไม่เกิน 5MB)',
    'prod.new.type': 'ประเภทสินค้า',
    'prod.new.typePhysical': 'หนังสือเล่ม (Physical)',
    'prod.new.typeEbook': 'อีบุ๊ก (E-Book)',
    'prod.new.status': 'สถานะการแสดงผล',
    'prod.new.statusActive': 'แสดงผล (Active)',
    'prod.new.statusDraft': 'ซ่อน (แบบร่าง)',
    'prod.new.cancel': 'ยกเลิก',
    'prod.new.save': 'บันทึกสินค้าใหม่',

    // Purchase Orders
    'po.title': 'ใบสั่งซื้อ (Purchase Orders)',
    'po.subtitle': 'สร้างและจัดการใบสั่งซื้อสินค้าจากซัพพลายเออร์',
    'po.add': 'สร้างใบสั่งซื้อใหม่',
    'po.search': 'ค้นหาเลข PO, ซัพพลายเออร์...',
    'po.col.id': 'เลข PO',
    'po.col.supplier': 'ซัพพลายเออร์',
    'po.col.date': 'วันที่สร้าง',
    'po.col.expected': 'กำหนดรับ',
    'po.col.total': 'ยอดรวม',
    'po.col.status': 'สถานะ',
    'po.col.actions': 'จัดการ',
    'po.filter.all': 'ทั้งหมด',
    'po.filter.pending': 'รอรับของ (Pending)',
    'po.filter.partial': 'รับบางส่วน (Partial)',
    'po.filter.completed': 'รับครบ (Completed)',
    'po.filter.cancelled': 'ยกเลิก (Cancelled)',

    // Users
    'usr.title': 'Users',
    'usr.subtitle': 'จัดการบัญชีผู้ใช้งานและสิทธิ์การเข้าถึง',
    'usr.search': 'ค้นหาผู้ใช้...',
    'usr.add': 'เพิ่มผู้ใช้งาน',
    'usr.col.user': 'ผู้ใช้งาน',
    'usr.col.contact': 'ข้อมูลติดต่อ',
    'usr.col.role': 'บทบาท',
    'usr.col.status': 'สถานะ',
    'usr.col.join': 'วันที่สมัคร',

    // Stock - Overview
    'stk.title': 'Inventory',
    'stk.subtitle': 'ตรวจสอบและจัดการสต็อกสินค้าคงคลัง',
    'stk.search': 'ค้นหาสินค้า...',
    'stk.col.product': 'สินค้า',
    'stk.col.inStock': 'มีในคลัง',
    'stk.col.reserved': 'ถูกจอง',
    'stk.col.available': 'พร้อมขาย',
    'stk.col.category': 'หมวดหมู่',
    'stk.col.cost': 'ต้นทุน',
    'stk.col.price': 'ราคาขาย',
    'stk.col.reorder': 'จุดสั่งซื้อ',
    'stk.col.lastUpdate': 'อัปเดตล่าสุด',
    'stk.action.add': 'ปรับสต็อก',
    'stk.new': 'รับสินค้าเข้า (PO)',
    'stk.tab.all': 'ทั้งหมด',
    'stk.tab.inStock': 'มีสต็อก',
    'stk.tab.low': 'ใกล้หมด',
    'stk.tab.out': 'หมดสต็อก',
    'stk.card.totalSku': 'จำนวน SKU ทั้งหมด',
    'stk.card.totalValue': 'มูลค่าสต็อกรวม',
    'stk.card.lowAlert': 'แจ้งเตือนสต็อกต่ำ',
    'stk.card.outOfStock': 'สินค้าหมดสต็อก',
    'stk.adjust.title': 'ปรับจำนวนสต็อก',
    'stk.adjust.current': 'จำนวนปัจจุบัน',
    'stk.adjust.type': 'ประเภทการปรับ',
    'stk.adjust.add': 'เพิ่ม (+)',
    'stk.adjust.remove': 'ลด (-)',
    'stk.adjust.set': 'ตั้งค่าใหม่',
    'stk.adjust.qty': 'จำนวน',
    'stk.adjust.reason': 'เหตุผล',
    'stk.adjust.reasonPh': 'เช่น ตรวจนับสต็อก, สินค้าชำรุด, คืนสินค้า...',
    'stk.adjust.save': 'บันทึกการปรับ',
    'stk.adjust.cancel': 'ยกเลิก',
    'stk.log.title': 'ประวัติ Stock Movement',
    'stk.log.date': 'วันที่',
    'stk.log.type': 'ประเภท',
    'stk.log.qty': 'จำนวน',
    'stk.log.ref': 'อ้างอิง',
    'stk.log.by': 'โดย',
    'stk.log.balance': 'คงเหลือ',
    // Stock - Receive (PO)
    'stk.receive.title': 'รับสินค้าเข้าคลัง (PO)',
    'stk.receive.subtitle': 'บันทึกการรับสินค้าผ่านใบสั่งซื้อ (Purchase Order)',
    'stk.receive.step1': '1. เลือก PO',
    'stk.receive.step2': '2. กรอกจำนวน',
    'stk.receive.step3': '3. ยืนยัน',
    'stk.receive.step4': '4. เสร็จสิ้น',
    'stk.receive.searchPo': 'ค้นหาเลข PO หรือ Supplier...',
    'stk.receive.poList': 'ใบสั่งซื้อที่รอรับสินค้า',
    'stk.receive.poNumber': 'เลขที่ PO',
    'stk.receive.supplier': 'ซัพพลายเออร์',
    'stk.receive.expectedDate': 'วันที่คาดว่าจะได้รับ',
    'stk.receive.totalItems': 'จำนวน SKU',
    'stk.receive.poValue': 'มูลค่า PO',
    'stk.receive.actionSelect': 'เลือกรับสินค้า',
    'stk.receive.back': 'ย้อนกลับ',
    'stk.receive.next': 'ถัดไป',
    'stk.receive.item': 'สินค้า (SKU)',
    'stk.receive.ordered': 'จำนวนสั่ง',
    'stk.receive.good': 'รับจริง (ดี)',
    'stk.receive.damaged': 'ชำรุด',
    'stk.receive.diff': 'ส่วนต่าง',
    'stk.receive.note': 'หมายเหตุ',
    'stk.receive.unitCost': 'ต้นทุน/หน่วย',
    'stk.receive.lineTotal': 'มูลค่ารวม',
    'stk.receive.summaryTotal': 'รวมทั้งหมด',
    'stk.receive.reviewTitle': 'ตรวจสอบก่อนบันทึก',
    'stk.receive.reviewWarn': 'พบส่วนต่างในบางรายการ กรุณาตรวจสอบอีกครั้ง',
    'stk.receive.confirmBtn': 'ยืนยันและบันทึกเข้าคลัง',
    'stk.receive.grnNumber': 'เลข GRN',
    'stk.receive.successTitle': 'บันทึกรับสินค้าสำเร็จ!',
    'stk.receive.successSub': 'ระบบอัปเดตจำนวนสต็อกและสถานะใบสั่งซื้อเรียบร้อยแล้ว',
    'stk.receive.backToStock': 'กลับไปหน้าคลังสินค้า',
    'stk.receive.viewLog': 'ดู Movement Log',
    'stk.receive.printGrn': 'พิมพ์ GRN',

    // Tickets
    'tck.title': 'Support Tickets',
    'tck.subtitle': 'จัดการคำร้องเรียนและปัญหาจากลูกค้า',
    'tck.search': 'ค้นหาคำร้องเรียน...',
    'tck.col.details': 'รายละเอียด',
    'tck.col.customer': 'ลูกค้า / คำสั่งซื้อ',
    'tck.col.date': 'วันที่เปิดเรื่อง',
    'tck.action.review': 'ตรวจสอบ',
    'tck.empty': 'ไม่มีคำร้องเรียนในระบบ',
    'tck.detail.title': 'รายละเอียดคำร้อง',
    'tck.detail.orderRef': 'เลขอ้างอิงคำสั่งซื้อ',
    'tck.detail.subject': 'หัวข้อ',
    'tck.detail.message': 'รายละเอียด',
    'tck.detail.updateStatus': 'อัปเดตสถานะ:',
    'tck.status.open': 'เปิด (Open)',
    'tck.status.progress': 'รอดำเนินการ (In Progress)',
    'tck.status.close': 'ปิดแล้ว (Closed)',
    'tck.close': 'ปิดหน้าต่าง',
  },
  en: {
    // Layout
    'layout.loading': 'Loading Workspace...',
    'layout.overview': 'Overview',
    'layout.dashboard': 'Dashboard',
    'layout.reports': 'Reports & Stats',
    'layout.storeManagement': 'Store Management',
    'layout.orders': 'Orders',
    'layout.products': 'Products',
    'layout.purchaseOrders': 'Purchase Orders',
    'layout.stock': 'Inventory (Stock)',
    'layout.ebooks': 'E-Books',
    'layout.categories': 'Categories',
    'layout.promotions': 'Promotions',
    'layout.customerRelation': 'Customer Relations',
    'layout.users': 'Users',
    'layout.chat': 'Chat Messages',
    'layout.tickets': 'Support Tickets',
    'layout.reviews': 'Product Reviews',
    'layout.logout': 'Logout',
    'layout.title': 'Admin Workspace',
    'layout.subtitle': 'Manage your store and customers efficiently.',
    'layout.storefront': 'View Storefront',

    // Dashboard
    'dash.title': 'Dashboard',
    'dash.subtitle': 'System overview and key statistics over the last 30 days',
    'dash.30days': 'Last 30 Days',
    'dash.7days': 'Last 7 Days',
    'dash.thisMonth': 'This Month',
    'dash.thisYear': 'This Year',
    'dash.export': 'Export PDF',
    'dash.stat1': 'Total Sales',
    'dash.stat2': 'New Orders',
    'dash.stat3': 'New Users',
    'dash.stat4': 'System Visits',
    'dash.trendTitle': 'Sales Trend',
    'dash.trendSub': 'Compare across different periods',
    'dash.trendSales': 'Sales (THB)',
    'dash.topProducts': 'Top Products',
    'dash.viewAll': 'View All',
    'dash.sold': 'Sold',
    'dash.noData': 'No sales data',

    // Orders
    'order.title': 'Orders',
    'order.subtitle': 'Manage orders and shipping statuses',
    'order.search': 'Search orders...',
    'order.filter': 'Filter',
    'order.tab.all': 'All Orders',
    'order.tab.pending': 'Pending Payment',
    'order.tab.verify': 'Verifying',
    'order.tab.processing': 'Processing',
    'order.tab.ready': 'Ready to Ship',
    'order.tab.shipped': 'Shipped',
    'order.col.id': 'Order ID',
    'order.col.date': 'Date',
    'order.col.customer': 'Customer',
    'order.col.total': 'Total',
    'order.col.status': 'Status',
    'order.col.actions': 'Actions',
    'order.action.waitPay': 'Awaiting Payment',
    'order.action.verify': 'Verify Payment',
    'order.action.packDone': 'Pack Done',
    'order.action.ship': 'Ship',
    'order.action.print': 'Print Label',
    'order.detail.title': 'Order Details',
    'order.detail.customer': 'Customer Info',
    'order.detail.shipMethod': 'Shipping Method',
    'order.detail.placedOn': 'Placed on:',
    'order.detail.tracking': 'Tracking Number',
    'order.detail.assignTracking': 'Assign Tracking',
    'order.detail.items': 'Order Items',
    'order.detail.paymentVerified': 'Payment Verified',
    'order.detail.payMethod': 'Method:',
    'order.detail.payTime': 'Time:',
    'order.detail.viewSlip': 'View Slip',
    'order.detail.cancel': 'Cancel',
    'order.detail.confirmShip': 'Confirm Shipment',
    'order.detail.done': 'Done',
    'order.empty': 'No Orders Found',

    // Categories
    'cat.title': 'Categories',
    'cat.subtitle': 'Manage product categories in the system',
    'cat.search': 'Search categories...',
    'cat.new': 'New Category',
    'cat.items': 'Items available',
    'cat.edit': 'Edit',

    // Products
    'prod.title': 'Products',
    'prod.subtitle': 'Manage all products in your store',
    'prod.add': 'Add Product',
    'prod.filter.all': 'All',
    'prod.filter.active': 'Active',
    'prod.filter.draft': 'Draft',
    'prod.search': 'Search products...',
    'prod.col.book': 'Book',
    'prod.col.type': 'Type',
    'prod.col.price': 'Price',
    'prod.col.status': 'Status',
    'prod.col.actions': 'Actions',
    'prod.new.title': 'Add New Book',
    'prod.new.subtitle': 'Add a new book to display on the storefront',
    'prod.new.basicInfo': 'Basic Information',
    'prod.new.name': 'Book Title',
    'prod.new.namePh': 'e.g. Harry Potter Book 1',
    'prod.new.author': 'Author',
    'prod.new.authorPh': 'Author Name',
    'prod.new.publisher': 'Publisher',
    'prod.new.publisherPh': 'Publisher Name',
    'prod.new.desc': 'Description',
    'prod.new.descPh': 'Synopsis or interesting details...',
    'prod.new.pricing': 'Pricing & Inventory',
    'prod.new.price': 'Selling Price (฿)',
    'prod.new.cost': 'Cost Price (฿)',
    'prod.new.sku': 'SKU',
    'prod.new.barcode': 'Barcode / ISBN',
    'prod.new.media': 'Cover Image',
    'prod.new.upload': 'Click to upload',
    'prod.new.uploadSub': 'or drag and drop (PNG, JPG up to 5MB)',
    'prod.new.type': 'Product Type',
    'prod.new.typePhysical': 'Physical Book',
    'prod.new.typeEbook': 'E-Book',
    'prod.new.status': 'Visibility Status',
    'prod.new.statusActive': 'Active (Visible)',
    'prod.new.statusDraft': 'Draft (Hidden)',
    'prod.new.cancel': 'Cancel',
    'prod.new.save': 'Save Product',

    // Purchase Orders
    'po.title': 'Purchase Orders',
    'po.subtitle': 'Create and manage purchase orders from suppliers',
    'po.add': 'Create PO',
    'po.search': 'Search PO number, supplier...',
    'po.col.id': 'PO Number',
    'po.col.supplier': 'Supplier',
    'po.col.date': 'Created Date',
    'po.col.expected': 'Expected Date',
    'po.col.total': 'Total',
    'po.col.status': 'Status',
    'po.col.actions': 'Actions',
    'po.filter.all': 'All',
    'po.filter.pending': 'Pending',
    'po.filter.partial': 'Partial',
    'po.filter.completed': 'Completed',
    'po.filter.cancelled': 'Cancelled',

    // Users
    'usr.title': 'Users',
    'usr.subtitle': 'Manage user accounts and access rights',
    'usr.search': 'Search users by name, email...',
    'usr.add': 'Add User',
    'usr.col.user': 'User',
    'usr.col.contact': 'Contact',
    'usr.col.role': 'Role',
    'usr.col.status': 'Status',
    'usr.col.join': 'Joined Date',

    // Stock - Overview
    'stk.title': 'Inventory',
    'stk.subtitle': 'Monitor and manage stock inventory',
    'stk.search': 'Search by name, SKU...',
    'stk.col.product': 'Product',
    'stk.col.inStock': 'In Stock',
    'stk.col.reserved': 'Reserved',
    'stk.col.available': 'Available',
    'stk.col.category': 'Category',
    'stk.col.cost': 'Cost',
    'stk.col.price': 'Sell Price',
    'stk.col.reorder': 'Reorder Pt.',
    'stk.col.lastUpdate': 'Last Updated',
    'stk.action.add': 'Adjust',
    'stk.new': 'Receive Stock (PO)',
    'stk.tab.all': 'All',
    'stk.tab.inStock': 'In Stock',
    'stk.tab.low': 'Low Stock',
    'stk.tab.out': 'Out of Stock',
    'stk.card.totalSku': 'Total SKUs',
    'stk.card.totalValue': 'Inventory Value',
    'stk.card.lowAlert': 'Low Stock Alerts',
    'stk.card.outOfStock': 'Out of Stock',
    'stk.adjust.title': 'Adjust Stock',
    'stk.adjust.current': 'Current Stock',
    'stk.adjust.type': 'Adjustment Type',
    'stk.adjust.add': 'Add (+)',
    'stk.adjust.remove': 'Remove (-)',
    'stk.adjust.set': 'Set New Value',
    'stk.adjust.qty': 'Quantity',
    'stk.adjust.reason': 'Reason',
    'stk.adjust.reasonPh': 'e.g. Physical count, damaged, customer return...',
    'stk.adjust.save': 'Save Adjustment',
    'stk.adjust.cancel': 'Cancel',
    'stk.log.title': 'Stock Movement History',
    'stk.log.date': 'Date',
    'stk.log.type': 'Type',
    'stk.log.qty': 'Qty',
    'stk.log.ref': 'Reference',
    'stk.log.by': 'By',
    'stk.log.balance': 'Balance',
    // Stock - Receive (PO)
    'stk.receive.title': 'Receive Stock (PO)',
    'stk.receive.subtitle': 'Record incoming inventory from Purchase Orders',
    'stk.receive.step1': '1. Select PO',
    'stk.receive.step2': '2. Input Qty',
    'stk.receive.step3': '3. Review',
    'stk.receive.step4': '4. Done',
    'stk.receive.searchPo': 'Search PO number or Supplier...',
    'stk.receive.poList': 'Pending Purchase Orders',
    'stk.receive.poNumber': 'PO Number',
    'stk.receive.supplier': 'Supplier',
    'stk.receive.expectedDate': 'Expected Date',
    'stk.receive.totalItems': 'SKUs',
    'stk.receive.poValue': 'PO Value',
    'stk.receive.actionSelect': 'Select PO',
    'stk.receive.back': 'Back',
    'stk.receive.next': 'Next',
    'stk.receive.item': 'Item (SKU)',
    'stk.receive.ordered': 'Ordered',
    'stk.receive.good': 'Good Qty',
    'stk.receive.damaged': 'Damaged',
    'stk.receive.diff': 'Diff',
    'stk.receive.note': 'Note',
    'stk.receive.unitCost': 'Unit Cost',
    'stk.receive.lineTotal': 'Line Total',
    'stk.receive.summaryTotal': 'Grand Total',
    'stk.receive.reviewTitle': 'Review Before Saving',
    'stk.receive.reviewWarn': 'Discrepancies detected. Please review highlighted items.',
    'stk.receive.confirmBtn': 'Confirm & Save Stock',
    'stk.receive.grnNumber': 'GRN Number',
    'stk.receive.successTitle': 'Stock Received Successfully!',
    'stk.receive.successSub': 'Inventory and PO status have been updated.',
    'stk.receive.backToStock': 'Back to Inventory',
    'stk.receive.viewLog': 'View Movement Log',
    'stk.receive.printGrn': 'Print GRN',

    // Tickets
    'tck.title': 'Support Tickets',
    'tck.subtitle': 'Manage customer complaints and issues',
    'tck.search': 'Search tickets...',
    'tck.col.details': 'Ticket Details',
    'tck.col.customer': 'Customer / Order',
    'tck.col.date': 'Date Opened',
    'tck.action.review': 'Review',
    'tck.empty': 'No tickets found',
    'tck.detail.title': 'Ticket Details',
    'tck.detail.orderRef': 'Order Reference',
    'tck.detail.subject': 'Subject',
    'tck.detail.message': 'Message Detail',
    'tck.detail.updateStatus': 'Update Status:',
    'tck.status.open': 'Open',
    'tck.status.progress': 'In Progress',
    'tck.status.close': 'Closed',
    'tck.close': 'Close',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('th');

  useEffect(() => {
    // Check local storage for saved language
    const saved = localStorage.getItem('adminLang');
    if (saved && (saved === 'th' || saved === 'en')) {
      setLang(saved);
    }
  }, []);

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('adminLang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
